{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cosmocloud-deploy.fullname" . }}
  labels:
    {{- include "cosmocloud-deploy.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "cosmocloud-deploy.fullname" . }}
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
